#!/bin/bash
# Based on http://openweathermap.org/current

API_KEY="02303b2a7dcfd54afee563d38a9273cb"

# Check on http://openweathermap.org/find
CITY_ID="${BLOCK_INSTANCE}"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="℃"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  ICON=${ICON_SNOW}
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  ICON=${ICON_RAINY}
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  ICON=${ICON_CLOUDY}
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  ICON=${ICON_SUNNY}
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  ICON=${ICON_FOG}
else
  ICON=${WEATHER_MAIN}
fi

DATE=$(date '+%d-%m-%Y %H:%M')

  echo "${DATE} 〉  ${ICON} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
echo "${DATE} 〉  ${ICON} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
echo ""

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
