alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
alias la='ll'
alias y='yaourt'
alias ys='yaourt -Ss'
alias yi='yaourt -S'
alias yin='yi --noconfirm'
alias yu='yaourt -Syua'
alias yun='yu --noconfirm'
alias yunf='yun --force'
alias yp='yaourt -Qm'
alias yr='yaourt -R'
alias wgup='sudo wg-quick up wg0-client'
alias wgdown='sudo wg-quick down wg0-client'
alias ovpnup='sudo openvpn /etc/openvpn/streisand.ovpn &'
alias ovpndown='sudo killall openvpn'
alias mountWindows='sudo mount /dev/sda4 /windows'
alias emptyTrash='rm -rf ~/.local/share/Trash/*'
alias dotfiles='(cd ~/dotfiles && vim -c NERDTree)'
alias grep="grep --color=auto"
alias restartX="systemctl restart lightdm"
